#!/bin/sh -Cue

git config --global --unset commit.template
git config --global --unset core.attributesFile
git config --global --unset core.excludesPath
git config --global --unset core.hooksPath
git config --global --unset init.templateDir
