#!/bin/sh
remote="$1"
url="$2"
zero=$(git hash-object --stdin </dev/null|  tr '0-9a-f' '0')
while read -r local_ref local_oid remote_ref remote_oid;do
if  test "$local_oid" = "$zero";then
:
else
if   test "$remote_oid" = "$zero";then
range="$local_oid"
else
range="$remote_oid..$local_oid"
fi
commit=$(  git rev-list -n 1 -i --grep '^WIP' "$range")
if   test -n "$commit";then
echo    >&2 "Found WIP commit in $local_ref, not pushing"
exit    1
fi
fi
done
if command -v git-lfs >/dev/null 2>&1;then
git  lfs pre-push "$@"
else
cat  >&2 <<-EOF
		This repository is configured for Git LFS but 'git-lfs' was not found on your path.
		If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
	EOF
exit  2
fi
